
GET http://localhost:3000/books
Content-Type: application/json

###

POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Swift",
  "price": 29.00
}

###

DELETE  http://localhost:3000/books/5e15d672316a9225e0fbb3af
Content-Type: application/json

###

PUT http://localhost:3000/books/5e15c409a19c901f6d09f683
Content-Type: application/json

{
  "title": "JavaScript: The Good Part",
  "price": 99.00
}